### ISSUE TITLE
Check Open Conference System

### ISSUE THREAD

**Issue by xmnlab** [scipy-latinamerica/scipyla2016#27]
Check the functionalities and usability of open conference system (https://pkp.sfu.ca/ocs/)

**Comment by rgaiacs** [comment]
@xmnlab We are going to use https://github.com/scipy-latinamerica/website-scipyla2016 because
1. it will save us time testing and developing a conference system;
2. ensure that we have a closer look to SciPy Conference (US); and
3. create opportunities to collaborate with people involved at SciPy Conference (US) organization.
