### ISSUE TITLE
Review documentation about translation

### ISSUE THREAD

**Issue by rgaiacs** [scipy-latinamerica/scipyla2016#46]
@knabben Could you review https://github.com/scipy-latinamerica/website-scipyla2016#translation?

We could detect the language much better but there are many other things to be done so I prefer that we don't spend time on it.

**Comment by knabben** [comment]
Django will discovery the main language via /django/utils/translation/trans_real.py:421 for the sublang. 

We can keep the es, pt, en folders. The other thing is: Django on the discovery steps will gonna probably get the language via Accept-Language header request, so changing browser configuration is enough for internationalization.

I think it is fair to point the old 1.4 documentation since its the version we are using on requirements.txt

**Comment by rgaiacs** [comment]
@knabben Thanks very much. :heart:
